### ISSUE TITLE
Support for group item (dimmer)?

### ISSUE THREAD

**Issue by RafalLukawiecki** [MitchMcKean/mccontrol#2]
Thank you for this useful extension! I have managed to make it work with a Switch item, but it does not seem to work with a Group item that I expected to behave as a dimmer. I am configuring it for item `g_Lights_Studio_Ceiling_Dimmers`. This is what the REST page for this item returns (with the URL obfuscated):

`
{"members":[{"link":"https://****/rest/items/hue_Studio_Ceiling_Desk_Dimmer","state":"100","stateDescription":{"pattern":"%d %%","readOnly":false,"options":[]},"type":"Dimmer","name":"hue_Studio_Ceiling_Desk_Dimmer","label":"Studio Ceiling Desk Dimmer","category":"light","tags":[],"groupNames":["g_Lights_Studio","g_Lights","g_Lights_Studio_Ceiling_Dimmers"]},{"link":"****/rest/items/hue_Studio_Ceiling_Wall_Dimmer","state":"100","stateDescription":{"pattern":"%d %%","readOnly":false,"options":[]},"type":"Dimmer","name":"hue_Studio_Ceiling_Wall_Dimmer","label":"Studio Ceiling Wall Dimmer","category":"light","tags":[],"groupNames":["g_Lights_Studio","g_Lights","g_Lights_Studio_Ceiling_Dimmers"]}],"groupType":"Dimmer","function":{"name":"AVG"},"link":"https://****/rest/items/g_Lights_Studio_Ceiling_Dimmers","state":"100.00000000","stateDescription":{"pattern":"%d %%","readOnly":false,"options":[]},"editable":false,"type":"Group","name":"g_Lights_Studio_Ceiling_Dimmers","label":"Studio Ceiling","category":"light","tags":[],"groupNames":[]}
`

I would like to be able to switch it on and off. If there is a way of controlling that, it would be nice to be able to change its dimmer and colour values, but that may not be possible using simple StreamDeck buttons.

Either way, thanks!

**Comment by MitchMcKean** [comment]
First of all thank you, I am glad you like what I build. 

For your use case you would need some advanced features which I have not implemented yet but I planned them for the future. 
Currently the only way you could go, is setting up some additional switches in your openHab and connect them with rules. 
In McContol I only implemented sending plain "ON" and "OFF" to the endpoints. 

For example, create a additional Switch in OpenHab and bind it to a rule, if the switch gets turned on, set up a rule for then turning the lights to 80% or changing the color to red. 

However currently I don't have time to update McControl but I will as soon it's possible.

**Comment by RafalLukawiecki** [comment]
Thank you. How come the ON and OFF don’t work with the Group item? I would have thought that with the above it should be possible to turn the group on or off?

**Comment by MitchMcKean** [comment]
Because you need a group switch or rule for that. 
Please read here for more info https://community.openhab.org/t/group-switch-or-on-off-vs-group/37325
